version: '3.8'

services:
  nginx:
    image: nginx:1.22-alpine
    restart: always
    container_name: site-jved-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  php:
    build: .
    volumes:
      - .:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
  mysql:
    image: mysql:8
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jveddb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      UPLOAD_LIMIT: 20M
    ports:
      - "8081:80"
    depends_on:
      - mysql
  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  dbdata: